### ISSUE TITLE
prokrustean_access format question

### ISSUE THREAD

**Issue by dkoslicki** [KoslickiLab/prokrustean#15]
For the FASTA file:
```
$ cat small.fa
>1
ACCCT
>2
GACCC
>3
TCCCG
```
After running a bwt on it and building a prokrustean graph:
```
 ./prokrustean/build/prokrustean -i small.fa.bwt.optbwt -l 1
```
I tried the following for prokrustean_access:
```
./prokrustean/build/prokrustean_access -i small.fa.bwt.optbwt
Input bwt file: small.fa.bwt.optbwt
Output sequences file: small.fa.bwt.optbwt.prokrustean.sequences
threads: 8
wavelet tree construction ...
4ms
characters(5): $ (3) A (2) C (9) G (2) T (2)  total 18
recover sequences from bwt... 1ms
indexing sequences (small.fa.bwt.optbwt.prokrustean.sequences) ...
0ms
```
And while it completes without error, the file contents appear... messy
```
 dmk333@e5-cse-cbdmk02:/scratch/dmk333_new/temp/temp$ more small.fa.bwt.optbwt.prokrustean.sequences
I am Prokrustes. Do not confuse me with the greek creature - Procrustes. I hate him.cumulative_countssuperblockmini_or_longlongsuperblockminisuperblo
ck▒?▒?small.fa.bwt.optbwt.prokrustean.sequences9@GACCCTGACCCTCCCG
PuTTYPuTTYPuTTY
```
Is this either: a) a bug or b) intended since it appears it _could_ be a binary file that is used elsewhere?

```

**Comment by akp6031** [comment]
Yes, it is intended to have a binary format, in order to identify metadata with its precise locations.
For example, to check if it is an access file generated by our ./prokrustean.access, I am storing a metadata "I am Prokrustes...." to check if it is authentic, and hence is not a bwt or a Prokrustean graph file for example. 
At initial stages, I planned more complicated information to be added in the file, e.g. strings of not only sequences but strata, where the complicated use cases made me to consider rigorous and complex structure. However, due to the time limitation, I am back to that simple structure with the sequences recovered from the bwt only, so maybe we can use a text format if you think potential users will prioritize it.

**Comment by dkoslicki** [comment]
Ah, I see. In that case, I don't think there's any particular reason to change the format. Perhaps in the help description, file name, or other places, an indication that this is a binary file format would help users not see the ".sequences" extension and think it's actually the ASCII sequences

**Comment by akp6031** [comment]
I will change the name and add some description in the readme. 
The naturally generated file name is in the form {INPUT}.bwt.**prokrustean.sequences**.
I will change it to {INPUT}.bwt.**sequences.dat** or maybe {INPUT}.bwt.**sequences.bin**.
